org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.252
neo_version_range=[21,)
loader_version_range=[4,)
curios_version=9.5.1+1.21.1
mod_id=sprintutilities
mod_name=sprint-utilities
mod_license=MIT
mod_version=1.0
mod_group_id=org.midnight
mod_authors=MidnightKittens
mod_description=Utilities for controlling sprint